### ISSUE TITLE
No implementations provided for Usedef and Callgraph

### ISSUE THREAD

**Issue by berezovskyi** [timed-c/ktc#1]
Hi, I got the following error while compiling ktc:

```
+ ocamlfind ocamlopt -linkpkg -package cil -I src src/ktcutil.cmx src/fdelay.cmx src/ktcoptions.cmx src/sdelay.cmx src/main.cmx -o src/main.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Usedef referenced from src/ktcutil.cmx
         Callgraph referenced from src/fdelay.cmx, src/sdelay.cmx
Command exited with code 2.
```

SW:

- macOS 10.13.2
- OCaml 4.06.0
- opam 1.2.2
- cil (git source w/patch for OCaml 4.06 https://github.com/cil-project/cil/pull/38)

**Comment by saranya-natarajan** [comment]
Hi
Are you executing make with sudo ? Can you execute it without and see if you get the same error ?

**Comment by berezovskyi** [comment]
fails in a same way with and w/o sudo
